### ISSUE TITLE
Creating a NullSessionInterface errors

### ISSUE THREAD

**Issue by pgjones** [xmrdsc/quart-session#1]
On [this line](https://github.com/xmrdsc/quart-session/blob/master/quart_session/__init__.py#L133) the `NullSessionInterface` is created without any arguments, specifically not a [`key_prefix`](https://github.com/xmrdsc/quart-session/blob/master/quart_session/sessions.py#L75) which results in a `TypeError: init() missing 1 required positional argument: 'key_prefix'` error.

See also https://github.com/pgjones/quart/issues/105

**Comment by xmrdsc** [comment]
Thanks for the report!
